import styles from "./layout.module.css"
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={styles["html"]}>
      <body className={styles["body"]}>{children}</body>
    </html>
  );
}
